print ("Produtos: Camisas, Calças e Tênis")
produto = input ("Qual produto você deseja?")
cor = input("Qual a cor desejada?")
print("Valores a vista 79 combo")
quanto = input ("Qual a quantidade desejada?")
print("Você realizou a compra de",produto, cor, "e o valor total é de", int (quanto) * 79)
